name: bootjack_datepicker
version: 1.0.1+3
authors: 
- Jimmy Shiau <jimmyshiau@potix.com>
- Tom Yeh <tomyeh@rikulo.org>
description: Bootjack datepicker component is a datepicker component of Bootjack.
homepage: https://github.com/rikulo/bootjack-datepicker
documentation: http://www.dartdocs.org/documentation/bootjack_datepicker/1.0.1
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  dquery: any
  bootjack: any
  intl: any
  rikulo_commons: any
